name: release

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/release.yml'
      - '**/dist/**'
      - 'action.yml'
      - 'yarn.lock'

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - run: yarn
      - run: yarn build
      - name: Setup git identity
        env:
          GH_RELEASE_TOKEN: ${{ secrets.SEMANTIC_RELEASE }}
        run: |
          git config --local user.name "bryantbiggs"
          git config --local user.email "${{ secrets.EMAIL }}"
          git remote set-url origin "https://${GITHUB_ACTOR}:${GH_RELEASE_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          echo "Git remote origin URL: $(git remote get-url origin)"

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.SEMANTIC_RELEASE }}
        run: yarn release
